site_name: Quantum PHP Framework
site_description: Documentation for Quantum PHP Framework v3.0

docs_dir: .rtd-docs
site_dir: site

theme:
  name: readthedocs

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

exclude_docs: |
  AGENTS.md

use_directory_urls: true
